//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastHTTP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbeddedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbeddedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastHTTP.EmbeddedResources", typeof(EmbeddedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///        &lt;title&gt;${title}&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;center&gt;
        ///            &lt;h2&gt;${title}&lt;/h2&gt;
        ///			${message}
        ///			&lt;hr&gt;
        ///        &lt;/center&gt;
        ///        &lt;i&gt;FastHTTP Server v1.0&lt;/i&gt;
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string error_page_template {
            get {
                return ResourceManager.GetString("error_page_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Default mimetypes file
        ///txt text/plain
        ///html text/html
        ///js text/javascript
        ///png image/png
        ///jpeg image/jpeg
        ///jpg image/jpg
        ///exe application/octet-stream
        ///mp4 video/mp4
        ///css text/css
        ///gif image/gif
        ///eot application/vnd.ms-fontobject
        ///htm text/html
        ///json application/json
        ///mjs text/javascript
        ///ogg audio/ogg
        ///woff font/woff
        ///woff2 font/woff2
        ///xml application/xml
        ///zip application/zip
        ///ttf font/ttf
        ///otf font/otf
        ///sh application/x-sh
        ///aac audio/aac
        ///tif image/tiff
        ///tiff image/tiff
        ///log text/plain
        ///pdf application [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mimetypes {
            get {
                return ResourceManager.GetString("mimetypes", resourceCulture);
            }
        }
    }
}
